<%@ Page Language="C#" %>
<html xmlns="http://www.w3.org/1999/xhtml">

<head id="Head1" runat="server"><meta http-equiv="pragma" content="no-cache" />
<LINK REL="stylesheet" TYPE="text/css" HREF="Style/Style.css">
<title>Chat - Customer Module</title>

</head>

<body>

<div id="wrapper">
    <div id="menu">
        <p class="welcome">Welcome, <b></b></p>
        <p class="logout"><a id="exit" href="#">Exit Chat</a></p>
        <div style="clear:both"></div>
    </div>
     
    <ul id="chatbox"></ul>
     
    <div class="container">
        <input type="text" id="message" />
        <input type="button" id="sendmessage" value="Send" />
        <input type="hidden" id="displayname" />
        
    </div>
</div>
<!--Script references. -->
    <!--Reference the jQuery library. -->
    <script src="/Scripts/jquery-1.6.4.min.js" ></script>
    <!--Reference the SignalR library. -->
    <script src="/Scripts/jquery.signalR-1.1.4.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="/signalr/hubs"></script>
    <!--Add script to update the page and send messages.--> 
    <script type="text/javascript">
        $(function () {
            // Declare a proxy to reference the hub. 
            var chat = $.connection.chatHub;
            var n;
            // Create a function that the hub can call to broadcast messages.
            chat.client.broadcastMessage = function (name, message) {
                // Html encode display name and message. 
                var encodedMsg = $('<div />').text(message).html();
                // Add the message to the page.
                $('#chatbox').append('<li>'+ name
                    + ':&nbsp;&nbsp;' + encodedMsg +'</li>');
            };
         
            // Get the user name and store it to prepend to messages.

           // n = prompt('Enter your name:', '');
            // Set initial focus to message input box.  
            $('#message').focus();
            // Start the connection.
            $.connection.hub.start().done(function () {
                $('#sendmessage').click(function () {
                    // Call the Send method on the hub. 
                    chat.server.send('ghada', $('#message').val());
                    // Clear text box and reset focus for next comment. 
                    $('#message').val('').focus();
                  

               

                });
               
            });
        });

        //creer un fichier

        function download(name, type) {
            var a = document.getElementById("a");
            var file = new Blob(['/'], { type: type });
            a.href = URL.createObjectURL(file);
            a.download = name;
        }
       
   
</script>
      
           
      <button onclick="download('d.txt', 'text/plain')">Create file</button>
<a href="" id="a">Cliquez ici pour télécharger votre fichier</a>
     
   
</body>


</html>